// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Why: Next.js reads `.env.local` for secrets; Prisma CLI only loaded `.env` by default.
// Load both so `npx prisma` uses the same URLs as `next dev` without duplicating vars.
config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Why: Vercel build machines cannot reach Supabase's direct connection (port 5432)
    // due to networking restrictions. MIGRATE_DATABASE_URL should point to Supabase's
    // session pooler URL (Settings → Database → Connection string → Session mode) which
    // IS reachable from build machines AND supports DDL/transactions needed for migrations.
    // Falls back to DATABASE_URL for local dev where direct connections work fine.
    url: process.env["MIGRATE_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
